### ISSUE TITLE
Add movie

### ISSUE THREAD

**Issue by alagunambi** [rinoldsimon/imdb-tamil#4]
Need option to add movies and display the available movies.

**Comment by alagunambi** [comment]
Done? I couldnt see any new code push.

**Comment by rinoldsimon** [comment]
my net is  damn slow here..... sorry... pushed now!!..

On Tue, Jun 24, 2014 at 9:46 AM, Alagunambi Welkin <notifications@github.com

**Comment by rinoldsimon** [comment]
you can add , list movie  under the movie tab in topbar section..
http://imdb-tamil.herokuapp.com/
